[build]
  base = "productividad-app"
  publish = "frontend"  # O "frontend/dist" si generas algo ahí
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
   from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
