[build]
  publish = "productividad-app/frontend"
  command = "npm install"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
